export const sampleData = {
  topics: [
    "Physical Quantities and Units",
    "Graphical Representation of Data",
    "Measurement of Physical Quantities",
    "Motion in a Straight Line",
    "Laws of Motion",
    "Work, Energy, and Power",
    "Rotational Motion",
    "Gravitation",
    "Properties of Matter",
    "Heat and Thermodynamics",
    "Oscillations and Waves",
    "Electrostatics",
    "Current Electricity",
    "Magnetism and Magnetic Effects of Current",
    "Electromagnetic Induction",
    "Optics",
    "Modern Physics",
  ],
  youtubePlaylist: ["Playlist 1", "Playlist 2"],
  pyq: ["AKTU Paper", "Previous STs Papers"],
  notes: ["Notes - Mansi Mam", "Notes - Sahil Sir"],
  ppt: ["PPT - Mansi Mam", "PPT - Sahil Sir"],
  importantTopics: [
    "Physical Quantities and Units",
    "Graphical Representation of Data",
    "Measurement of Physical Quantities",
    "Motion in a Straight Line",
    "Laws of Motion",
    "Work, Energy, and Power",
  ],
};
