export const allEvents = [
  {
    type: "classroomEvents",
    status: "ongoing",
    title: "AI Workshop",
    organizer: "Prof. John Doe",
    description: "Workshop to introduce the basics of AI.",
    details: "This workshop will cover the fundamentals of Artificial Intelligence, including supervised learning, unsupervised learning, and deep learning techniques. Participants will have hands-on sessions to explore AI models and algorithms.",
    imageUrl: "class.webp",
  },
  {
    type: "classroomEvents",
    status: "ongoing",
    title: "Live Coding Session",
    organizer: "Dr. Sarah Lee",
    description: "A live coding session to build a real-world application.",
    details: "In this session, the instructor will guide participants through building a real-world application, from initial concept to deployment. It will cover best practices for coding, debugging, and optimization.",
    imageUrl: "class.webp",
  },
  {
    type: "classroomEvents",
    status: "ongoing",
    title: "Advanced AI Workshop",
    organizer: "Dr. Alan Turing",
    description: "Workshop on advanced AI techniques and machine learning.",
    details: "This workshop dives deep into advanced AI techniques such as reinforcement learning, generative adversarial networks (GANs), and neural networks. It’s intended for participants with prior AI experience.",
    imageUrl: "class.webp",
  },
  {
    type: "classroomEvents",
    status: "upcoming",
    title: "Data Science Bootcamp",
    organizer: "Dr. Alan Turing",
    description: "Bootcamp focused on machine learning and data analysis.",
    details: "This bootcamp is designed to provide participants with a solid foundation in data science, covering topics like data preprocessing, machine learning algorithms, and data visualization techniques.",
    imageUrl: "class.webp",
  },
  {
    type: "classroomEvents",
    status: "upcoming",
    title: "Blockchain Technology Workshop",
    organizer: "Prof. Jane Smith",
    description: "Workshop to learn about blockchain and its applications.",
    details: "In this workshop, attendees will explore the fundamentals of blockchain technology, smart contracts, and its applications in industries like finance, healthcare, and supply chain management.",
    imageUrl: "class.webp",
  },
  {
    type: "classroomEvents",
    status: "upcoming",
    title: "Cybersecurity Basics",
    organizer: "Dr. Martin Green",
    description: "Introduction to cybersecurity and protection techniques.",
    details: "This session will cover the basics of cybersecurity, including encryption, network security, firewalls, and how to protect personal data. Real-world examples of cyberattacks will be discussed to highlight the importance of cybersecurity.",
    imageUrl: "class.webp",
  },

  {
    type: "codingEvents",
    category : "coding",
    status: "ongoing",
    title: "Hackathon 2025",
    organizer: "Tech Club",
    description: "A coding competition for developers to showcase their skills.",
    details: "Hackathon 2025 will bring together developers to collaborate, solve challenging problems, and create innovative solutions in a limited time. Teams will compete for exciting prizes and opportunities.",
    imageUrl: "coding.jpg",
  },
  {
    type: "codingEvents",
    category : "coding",
    status: "ongoing",
    title: "Code Wars",
    organizer: "Coding Society",
    description: "A competitive coding event with global participation.",
    details: "Code Wars will bring together programmers from across the world to solve algorithmic challenges in a competitive environment. Contestants will be ranked based on their performance.",
    imageUrl: "coding.jpg",
  },
  {
    type: "codingEvents",
    category : "coding",
    status: "ongoing",
    title: "Algorithms Challenge",
    organizer: "Tech Innovators",
    description: "Challenge to solve complex algorithmic problems.",
    details: "The Algorithms Challenge will test participants on their problem-solving skills using various data structures and algorithms. The event will feature difficult puzzles that require deep algorithmic knowledge.",
    imageUrl: "coding.jpg",
  },
  {
    type: "codingEvents",
    category : "coding",
    status: "upcoming",
    title: "AI Challenge",
    organizer: "Tech Innovators",
    description: "Challenge to solve problems using AI algorithms.",
    details: "This challenge will test participants' skills in artificial intelligence by presenting them with complex problems that can be solved using machine learning algorithms. Participants will need to design and train AI models to address these problems.",
    imageUrl: "coding.jpg",
  },
  {
    type: "codingEvents",
    category : "coding",
    status: "upcoming",
    title: "Web Dev Competition",
    organizer: "Web Wizards",
    description: "A competition to build innovative web applications.",
    details: "In this competition, participants will have the opportunity to build creative and innovative web applications. They will need to showcase their skills in HTML, CSS, JavaScript, and modern web frameworks.",
    imageUrl: "coding.jpg",
  },
  {
    type: "codingEvents",
    category : "coding",
    status: "upcoming",
    title: "Full-Stack Developer Contest",
    organizer: "Dev Hub",
    description: "Contest for building complete full-stack applications.",
    details: "This contest will challenge developers to build full-stack web applications, covering both the frontend and backend. Participants will be judged on the completeness of their projects and the technologies used.",
    imageUrl: "coding.jpg",
  },

  // College Events
  {
    type: "collegeEvents",
    category : "college",
    status: "ongoing",
    title: "Cultural Fest 2025",
    organizer: "Cultural Club",
    description: "An event celebrating the arts and cultural diversity.",
    details: "Cultural Fest 2025 will feature performances, art exhibits, and cultural displays celebrating the diversity of student life. It’s a great opportunity for students to showcase their artistic talents.",
    imageUrl: "college.png",
  },
  {
    type: "collegeEvents",
    category : "college",
    status: "ongoing",
    title: "Sports Meet",
    organizer: "Sports Council",
    description: "Annual sports competition for all students.",
    details: "The Sports Meet is an annual event where students participate in various athletic competitions, ranging from track and field to team sports. It’s a day of friendly competition and school spirit.",
    imageUrl: "college.png",
  },
  {
    type: "collegeEvents",
    category : "college",
    status: "ongoing",
    title: "Tech Expo",
    organizer: "Tech Society",
    description: "Exhibition of cutting-edge technologies and innovations.",
    details: "The Tech Expo will feature exhibits from startups and tech companies showcasing the latest innovations in technology. Students will have the chance to interact with industry professionals and see new products firsthand.",
    imageUrl: "college.png",
  },
  {
    type: "collegeEvents",
    category : "college",
    status: "upcoming",
    title: "Alumni Meet",
    organizer: "Student Union",
    description: "Alumni reunion with networking opportunities.",
    details: "The Alumni Meet will bring together former students of the collegeEvents for a reunion. It’s a great opportunity to network, share experiences, and create connections for future collaborations.",
    imageUrl: "college.png",
  },
  {
    type: "collegeEvents",
    category : "college",
    status: "upcoming",
    title: "Freshers Party",
    organizer: "Freshers Committee",
    description: "Welcome event for new students at the collegeEvents.",
    details: "The Freshers Party is an exciting event where new students are welcomed into the collegeEvents community. There will be music, games, and activities to help them meet new people and get to know the campus.",
    imageUrl: "college.png",
  },
  {
    type: "collegeEvents",
    category : "college",
    status: "upcoming",
    title: "Music Festival",
    organizer: "Music Club",
    description: "An event showcasing musical talent and performances.",
    details: "The Music Festival will feature performances from student bands, solo artists, and guest performers. It’s a celebration of musical talent and creativity within the collegeEvents community.",
    imageUrl: "college.png",
  },
];
